title: Control and LED with Scatch
hero_image: images/banner.png
description: Turn an LED on and off with Scratch
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
interests: "physical computing"
technologies: "scratch"
steps:
  - title: Control an LED
